version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y docker

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264420817.dkr.ecr.us-east-1.amazonaws.com/yadav-ecr

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t yadav-flask-app .
      - docker tag yadav-flask-app:latest 058264420817.dkr.ecr.us-east-1.amazonaws.com/yadav-ecr/yadav-flask-app:latest
      - docker push 058264420817.dkr.ecr.us-east-1.amazonaws.com/yadav-ecr/yadav-flask-app:latest

  post_build:
    commands:
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"flask-app","imageUri":"058264420817.dkr.ecr.us-east-1.amazonaws.com/yadav-ecr/yadav-flask-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'                 # Include all files in the current directory
    - imagedefinitions.json   # Explicitly include the imagedefinitions.json file
